### ISSUE TITLE
Database query built from user-controlled sources

### ISSUE THREAD

**Issue by ankityadavhere** [ankityadavhere/api#3]
```javascript
  try {
    const updatedStudent = await Student.findByIdAndUpdate(
      req.params.id,
      req.body,
```

file: src/routes/routes.js/#L41

Building a database query from user-controlled sources is vulnerable to insertion of malicious code by the user.

This query depends on a user-provided path, a malicious user may be able to run malicious database queries.

Potential fix: use of `$eq` like operators o ensure that untrusted data is interpreted as a literal value and not as a query object.

**Comment by ankityadavhere** [comment]
High priority stuff!

**Comment by AtulPatil-me** [comment]
Should I add a middleware function to validate the data?
This will fix the issue for now but as the database gets bigger the middleware function will bloat the codebase.
Another fix will be using some libraries.

**Comment by ankityadavhere** [comment]
i think mongodb has some inbuilt stuff for this 🤔

**Comment by ankityadavhere** [comment]
Another solution will be to treat the user data as a literal, not as a JSON object, this won't hard the database from malicious queries

**Comment by ankityadavhere** [comment]
JavaScript's [`escape()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) and [mongo-sanitize](https://github.com/vkarpov15/mongo-sanitize) are two good solutions to escape special characters

**Comment by AtulPatil-me** [comment]
We have already defined the schema for the object, so I think any malicious code will be automatically converted to a string.
Not sure tho

**Comment by ankityadavhere** [comment]
that's why opened this issue lmao

**Comment by AtulPatil-me** [comment]
![Ehh](https://tenor.com/view/george-lopez-confused-unsure-eh-meh-gif-9297878)

**Comment by AtulPatil-me** [comment]
Are you doing it?
What are you using mongo-sanitize?

**Comment by ankityadavhere** [comment]
Yep, mongo-sanitize

**Comment by ankityadavhere** [comment]
assigned to you!

**Comment by AtulPatil-me** [comment]
Me a noob at GitHub, if I do some weird stuff sambhal lena 😂

**Comment by ankityadavhere** [comment]
okie 😂
